name: build

on:
  workflow_dispatch:
    inputs:
      java_version:
        type: number
        default: 17

jobs:
  build:
    name: start weather station build
    runs-on: ubuntu-latest

    steps:
      - name: checkout source code
        uses: actions/checkout@v4

      - name: setup java
        uses: actions/setup-java@v3
        with: 
          distribution: corretto
          java-version: ${{ inputs.java_version}}

      - name: setup Docker
        uses: docker/setup-buildx-action@v2

      - name: build java project
        run: mvn package

      - name: build Docker image
        run: docker build -t latvia-weather-stations:latest .